services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: football-bet-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - D:/Coding/football_bet/dist/data/bets.json:/app/data/bets.json
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: football-bet-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  bets_data:
    driver: local
